export const icons = {
  camera: require('./source/camera.png'),
  delete: require('./source/delete.png'),
  edit: require('./source/edit.png'),
  gallery: require('./source/gallery.png'),
  logout: require('./source/logout.png'),
  about: require('./source/about.png'),
  key: require('./source/key.png'),
  languages: require('./source/languages.png'),
  schedule: require('./source/schedule.png'),
  userColored: require('./source/user_colored.png'),
  notification: require('./source/notification.png'),
  home: require('./source/home.png'),
  check: require('./source/check.png'),
  vietnam: require('./source/vietnam.png'),
  uk: require('./source/united-kingdom.png'),
  search: require('./source/search.png'),
  star: require('./source/star_24px.png'),
  heartOutline: require('./source/heartOutline.png'),
  path: require('./source/Path.png'),
  fastfood: require('./source/fastfood.png'),
  cash: require('./source/local_atm_24px.png'),
  timer: require('./source/timer.png'),
  doneAll: require('./source/done_all_24px.png'),
  doneWhite: require('./source/doneWhite.png'),
  heart: require('./source/heart.png'),
  rightArrow: require('./source/rightArrow.png'),
  leftArrow: require('./source/leftArrow.png'),
};

export type IconSource = keyof typeof icons;
